#!/bin/bash

#
# Configuration
#
PREFIX_DIR=/home/hadoop
SQLITE_PATH=/usr/bin
DB_NAME=kpi_cruscotto.db
TABLE_NAME=KPI_FE_CRUSCOTTO
ETL_EXE=$PREFIX_DIR/dev/etlv2/etlv2
CSV_FILES_PATH=$PREFIX_DIR/dev/etlv2/kpi_cruscotto/
CSV_FILE_TO_IMPORT=kpi_fe_unico.csv
CSV_FILES="201603_KPI_ALL_IP_MENSILE.csv	201603_KPI_CORE_MOBILE_MENSILE.csv	201603_KPI_UBB_ACCESS_ATM_MENSILE.csv	201603_KPI_UBB_ACCESS_CX_MENSILE.csv	201603_KPI_UBB_ACCESS_MOBILE_MENSILE.csv	201603_KPI_UBB_ACCESS_TX_MENSILE.csv"
#CSV_FILES="201602_KPI_ALL_IP_MENSILE.csv	201602_KPI_CORE_MOBILE_MENSILE.csv	201602_KPI_UBB_ACCESS_ATM_MENSILE.csv	201602_KPI_UBB_ACCESS_CX_MENSILE.csv	201602_KPI_UBB_ACCESS_MOBILE_MENSILE.csv	201602_KPI_UBB_ACCESS_TX_MENSILE.csv"
OUTPUT_FILE=kpi_fe_unico_preagg.csv

#
# import file into database
#
function import_data() {
  cd $CSV_FILES_PATH
  rm -f $DB_NAME
  rm -f "$CSV_FILE_TO_IMPORT".tmp
  touch "$CSV_FILE_TO_IMPORT".tmp
  for file in $CSV_FILES; do
    cat $file >>"$CSV_FILE_TO_IMPORT".tmp
  done
  sed '/DATA;SILOS;ISOLA;POLO;REGIONE;SEVERITY;DOMINIO;NETWORK;FAMIGLIA;SLOGAN;PIATTAFORMA;VENDOR;GRAYLIST;PICCOLI_ALLARMI;CORR_INTERD;ACK;ACK+TT;ACK+PARK;CORRELATO;PARKSISTEMA;OUTAGE;NON_GESTITI_NOTE;NON_GESTITI<60;NON_GESTITI>=60;VAI/d' "$CSV_FILE_TO_IMPORT".tmp >$CSV_FILE_TO_IMPORT
  echo "importing data from file "$CSV_FILE_TO_IMPORT
  $SQLITE_PATH/sqlite3 $CSV_FILES_PATH/$DB_NAME <<!
CREATE TABLE IF NOT EXISTS $TABLE_NAME (DATA DATE, SILOS TEXT, ISOLA TEXT, POLO TEXT, REGIONE TEXT, SEVERITY TEXT, DOMINIO TEXT, NETWORK TEXT, FAMIGLIA TEXT, SLOGAN TEXT, PIATTAFORMA TEXT, VENDOR TEXT, GRAYLIST SMALLINT, PICCOLI_ALLARMI SMALLINT,CORR_INTERD SMALLINT,ACK SMALLINT, ACKTT SMALLINT, ACKP SMALLINT, CORR SMALLINT, PSISTEMA SMALLINT, OUT SMALLINT, NGN SMALLINT, NGNMIN60 SMALLINT, NGNMAG60 SMALLINT, VAI INTEGER);
.separator ";"
.import $CSV_FILE_TO_IMPORT $TABLE_NAME
!

}

#
# Main Procedure
#
first_day_of_current_month=$($SQLITE_PATH/sqlite3 $CSV_FILES_PATH/$DB_NAME 'SELECT DATE("NOW","START OF MONTH")')
first_day_of_current_month="2016-03-01"
echo First day of current month is: $first_day_of_current_month
import_data;

# calcola i raggruppamenti mensili relativi al mese in corso
$ETL_EXE -a m -d $CSV_FILES_PATH/$DB_NAME -t $TABLE_NAME -m $first_day_of_current_month | dd of=$CSV_FILES_PATH/$OUTPUT_FILE bs=4K
